db:
 host: xxxxx
 port: 5432
 user: user_sankoh_insert
 password: xxxxx
 database: reservation_db_sankoh

code:
 ken_code:
  兵庫県: '280000'
 area_code:
  城崎・竹野・豊岡: '281100'
  姫路・赤穂・播磨: '280800'
  神戸・有馬・明石: '280200'
  淡路島: '281700'

mappings:
  reservation_counts:
     string:
      area_name: "エリア名"
      facility_name: "宿名"

      integer:
        facility_outer_id: "宿番号"
        number_of_reservations: "予約件数"

      date:
        acquisition_date: "予約日"

  
  reservation_price:
   string:
    area_name: "エリア名"
    #facility_name: "宿名"
    facility_outer_id: "宿番号"
    holiday_type: "平休区分"
    plan_name: "プラン名"
  
   integer:
    number_of_weeks_ahead: "リードタイム"
    price: "価格"

   date:
    acquisition_date: "予約日"
    acquisition_week_date: "予約週"

conditions:
  reservation_counts:
    lead_time_max: 3
    holiday_type: ["休前日","平日"]

  

webhook:
 name: bot_sankoh
 url: xxxxx